openapi: 3.0.0
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/abumarkub/filebundle/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/abumarkub/fllebundle/1.0.0
  - description: Docker test server
    url: 'http://localhost:8080/'
info:
  description: File Bundle API
  version: 1.0.0
  title: File Bundle API
  contact:
    email: daniel@tweedegolf.nl
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  '/admin/file/list/{id}':
    get:
      operationId: openFolder
      description: Returns files and folder in the folder whose id is in the path
      responses:
        '200':
          description: A list of files and folders.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list'
  '/admin/file/upload':
    post:
      operationId: upload
      description: Upload files to the server
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Successfully uploaded files
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uploadResponse'
  '/admin/file/move/{id}':
    post:
      operationId: moveItems
      description: moves items (files and/or folders) to the folder whose is in the path
      requestBody:
        content:
          multipart/form-data:
            schema:
              fileIds:
                type: array
                items: string
              folderIds:
                type: array
                items: string
      responses:
        200:
          description: the ids of the items that raised errors while moving will be returned
          content:
            application/json:
              schema:
                errors:
                  fileIds:
                    type: array
                    items: string
                  folderIds:
                    type: array
                    items: string
components:
  schemas:
    uploadResponse:
      properties:
        errors:
          type: object
          additionalProperties:
            type: string
            items:
              type: string
        uploads:
          type: array
          items:
            $ref: '#/components/schemas/file'
    error:
      properties:
        error:
          type: string
    list:
      properties:
        files:
          type: array
          items:
            $ref: '#/components/schemas/file'
        folders:
          type: array
          items:
            $ref: '#/components/schemas/folder'
    file:
      properties:
        id:
          type: string
        name:
          type: string
        create_ts:
            type: number
        created:
            type: string
        type:
            type: string
        size:
            type: string
        size_bytes:
            type: number
        original:
            type: string
        thumb:
            type: string
            nullable: true
        is_new:
            type: boolean
        is_trashed:
            type: boolean
      required:
        - id
        - name
    folder:
      properties:
        id:
          type: string
        name:
          type: string
        parent:
          oneOf:
          - type: string
          - nullable: true
        create_ts:
          type: integer
        created:
          type: string
        file_count:
         type: integer
        folder_count:
          type: integer
        type:
          type: string
        size:
          type: string
        size_bytes:
          type: integer
        is_trashed:
          type: boolean
      required:
        - id
        - name
        - parent
