openapi: 3.0.0
servers:
  - description: Docker test server
    url: 'http://localhost:8080/'
info:
  description: File Bundle API
  version: 1.0.0
  title: File Bundle API
  contact:
    email: daniel@tweedegolf.nl
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /admin/file/move:
    post:
      operationId: moveItems to root folder
      description: moves items (files and/or folders) to the root folder
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                fileIds:
                  type: array
                  items:
                    type: string
              example:
                fileIds:
                  - '38'
                  - '39'
            encoding:
              fileIds:
                contentType: application/json
                style: deepObject
                explode: true
      responses:
        '200':
          description: >-
            the ids of the items that raised errors while moving will be
            returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  file_errors:
                    type: array
                    items:
                      type: string
                  folder_errors:
                    type: array
                    items:
                      type: string
