imports:
    - { resource: ../config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/dev/routing.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    use_microseconds: false
    handlers:
        main:
            type: error_log
            message_type: 0
            level: debug
            channels: [!event]
        console:
            type:   console
            bubble: false
            channels: [!event, !doctrine]
        # uncomment to log to a file in the logs dir
        # main:
        #     type:  stream
        #     path:  %kernel.logs_dir%/%kernel.environment%.log
        #     level: debug
        #     channels: [!event]

        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        # firephp:
        #     type:  firephp
        #     level: info
        # chromephp:
        #     type:  chromephp
        #     level: info

#swiftmailer:
#  delivery_address: me@example.com
