api:
  openFolder: /admin/file/list/ # {id: string}
  uploadFiles: /admin/file/upload/ # {fileList: File[], parentFolderId: string}
  deleteFile: /admin/file/delete/ # {id :string}
  addFolder: /admin/file/create/folder/ # {name: string, parentFolderId: string}
  deleteFolder: /admin/file/delete/folder/ # {id: string}
  renameFolder: /admin/file/rename/folder/ # {id: string}
  moveItems: /admin/file/move/ # {fileIds: string[], folderIds: string []}
  emptyRecycleBin: /admin/file/recycle-bin/empty
