openapi: 3.0.0
servers:
  - description: Docker test server
    url: 'http://localhost:8080'
info:
  description: File Bundle API
  version: 1.0.0
  title: File Bundle API
  contact:
    email: daniel@tweedegolf.nl
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /admin/file/list:
    $ref: >-
      http://localhost:8080/assets/api/openapi_yaml/list_folder.yaml#/listRootFolder
  '/admin/file/list/{id}':
    $ref: >-
      http://localhost:8080/assets/api/openapi_yaml/list_folder.yaml#/listFolderById
  /admin/file/move:
    $ref: >-
      http://localhost:8080/assets/api/openapi_yaml/move_items.yaml#/moveToRootFolder
  '/admin/file/move/{id}':
    $ref: >-
      http://localhost:8080/assets/api/openapi_yaml/move_items.yaml#/moveToFolderById
  /admin/file/create/folder:
    $ref: >-
      http://localhost:8080/assets/api/openapi_yaml/create_folder.yaml#/createFolderInRootFolder
  '/admin/file/create/folder/{id}':
    $ref: >-
      http://localhost:8080/assets/api/openapi_yaml/create_folder.yaml#/createFolderInFolderById
  /admin/file/upload:
    $ref: >-
      http://localhost:8080/assets/api/openapi_yaml/upload.yaml#/uploadToRootFolder
  '/admin/file/upload/{id}':
    $ref: >-
      http://localhost:8080/assets/api/openapi_yaml/upload.yaml#/uploadToFolderById
  '/admin/file/delete/{id}':
    $ref: 'http://localhost:8080/assets/api/openapi_yaml/delete.yaml#/deleteFileById'
  '/admin/file/delete/folder/{id}':
    $ref: >-
      http://localhost:8080/assets/api/openapi_yaml/delete.yaml#/deleteFolderById
  '/admin/file/rename/folder/{id}':
    $ref: >-
      http://localhost:8080/assets/api/openapi_yaml/rename_folder.yaml#/renameFolderById
  /admin/file/metadata:
    $ref: 'http://localhost:8080/assets/api/openapi_yaml/metadata.yaml#/getMetaData'
  /admin/file/recycle_bin/empty:
    $ref: 'http://localhost:8080/assets/api/openapi_yaml/empty_recyclebin.yaml'
